import { ChakraProvider } from '@chakra-ui/react';
import Head from 'next/head';
import theme from '../../utils/theme';
import Header from '../Header';
import { Web3ReactProvider } from '@web3-react/core';
import { ethers } from 'ethers';

interface LayoutProps {
  children: React.ReactNode;
}

const getLibrary = (
  provider:
    | ethers.providers.ExternalProvider
    | ethers.providers.JsonRpcFetchFunc
) => {
  const library = new ethers.providers.Web3Provider(provider);
  library.pollingInterval = 8000;
  return library;
};

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <ChakraProvider theme={theme}>
        <Web3ReactProvider getLibrary={getLibrary}>
          <Head>
            <title>Recommender</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <Header />
          <main>{children}</main>
          <div> Footer </div>
        </Web3ReactProvider>
      </ChakraProvider>
    </>
  );
}
