import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Recommender</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="#">Recommender!</a>
				</h1>

				<p className={styles.description}>Check for candidate here!</p>
				<p className={styles.description}>Enter the provided wallet ID here</p>
			</main>

			<footer className={styles.footer}>
				<span>
					Made with <span className="heart">&hearts; </span> by Saphal
				</span>
			</footer>
		</div>
	)
}

export default Home
